# Generated by Django 4.2.4 on 2023-08-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='manufactuter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.manufactuter'),
        ),
    ]
