# Generated by Django 4.2.4 on 2023-08-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersale',
            name='image',
            field=models.ImageField(default='img/goods.png', upload_to='offer_image'),
        ),
    ]
