# Generated by Django 4.2.4 on 2023-08-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_offersale_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offersale',
            old_name='name',
            new_name='title',
        ),
    ]
