# Generated by Django 4.2.4 on 2023-08-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_offermodel_manufactuter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufactuter',
            new_name='Manufacturer',
        ),
        migrations.RenameField(
            model_name='offermodel',
            old_name='manufactuter',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='offersale',
            old_name='manufactuter',
            new_name='manufacturer',
        ),
    ]
