# Generated by Django 4.2.4 on 2023-08-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_offersale_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersale',
            name='image',
            field=models.ImageField(default='img/no_item_image.jpg', upload_to='offer_image'),
        ),
    ]
