# Generated by Django 4.2.4 on 2023-08-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_offersale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbuy',
            name='in_active',
            field=models.BooleanField(default=True),
        ),
    ]
